# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180125_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='name',
            field=models.CharField(default='restaurant', max_length=120),
            preserve_default=False,
        ),
    ]
