# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_cuisines'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisines',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
