# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_cuisines_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuisines',
            new_name='Cuisine',
        ),
    ]
